# Generated by Django 4.2.7 on 2025-12-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportconversation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('mixed', 'Mixed')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='language_detected',
            field=models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('mixed', 'Mixed')], max_length=5),
        ),
    ]
